### ISSUE TITLE
Relicense Repository - EPL+Apache

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-sdk-sample-scripts#4]
Sample script repositories are better suited with an EPL+Apache 2.0 dual license. See zowe/zowe-cli-sample-scripts#19. We should also add a LICENSE and LICENSE_HEADER along with automation to generate the license headers at the top of each file similar to [zowe/zowe-cli-sample-scripts](https://github.com/zowe/zowe-cli-sample-scripts).

**Comment by zFernand0** [comment]
Here is a PR we can use as an example:
- https://github.com/zowe/zowe-cli-sample-plugin/pull/61
